widget:
  # 控件版本（与POM文件定义同步）
  version: @project.version@
spring:
  aop:
    auto: false
  main:
    banner-mode: off
  thymeleaf:
    enabled: false
    cache: false
  jmx:
    enabled: false
  sql:
    init:
      enabled: false
  mvc:
    formcontent:
      filter:
        enabled: false
  servlet:
    multipart:
      enabled: false
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      min-spare: 4
      max: 4
  port: 19888
